######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 16 13:54:37 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG -= gui
CONFIG += console

QT     -= gui
QT     += console network

# Input
SOURCES += \ 
    main.cpp \
    server.cpp \
    serverthread.cpp

HEADERS += \
    server.h \
    serverthread.h \
    ../inc/protocol.h
