######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 16 16:32:34 2010
######################################################################

TEMPLATE = app
TARGET = tst_messages
DEPENDPATH += .
INCLUDEPATH += .

CONFIG -= gui
CONFIG += console qtestlib

QT     -= gui
QT     += console network

# Directories

SOURCES += \
    main.cpp

HEADERS += \
    TestMessage.h \
    ../inc/protocol.h \
    TestFile.h
