######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 13 01:03:33 2011
######################################################################

maemo5 {
  CONFIG += mobility12
} else {
  CONFIG += mobility
}
MOBILITY = systeminfo
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bat.h
SOURCES += bat.cpp main.cpp
